### ISSUE TITLE
Not visible after update to WP 5.6

### ISSUE THREAD

**Issue by cargeo** [bueltge/addquicktag#48] opened 2020-12-15 18:00 UTC
Since WP 5.6 the Quicktags field is no longer visible in editor. This is probably caused by WP's new jQuery library.

**Comment by bueltge** [comment] 2021-01-21 20:05
Hello @cargeo I tested it with WP 5.7-beta and it works, also in the Gutenberg editor, Classic Block, and if Gutenberg is inactive, classic Editor. In each test the visual and text mode work on the classic editor. In Gutenberg, the visible quicktags are existent.

![image](https://user-images.githubusercontent.com/133425/105406184-5c318e00-5c2c-11eb-88ad-c81bcb0ce983.png)

**Comment by cargeo** [comment] 2021-01-22 07:11
Tested in fresh WP 5.6 install: It’s visible in Gutenberg Classic Editor block, but not in Classic Editor when Gutenberg is disabled (Classic Editor plugin).

See Console screenshot. 

macOS 11.1
Chrome 88
<img width="916" alt="Screenshot-WP5 6-AddQuicktag-Console" src="https://user-images.githubusercontent.com/14090070/105458576-25d62c00-5c89-11eb-8c04-30cc95525c76.png">

**Comment by bueltge** [comment] 2021-01-22 07:45
I tested again with the Classic Editor Plugin to remove Gutenberg.
Text mode works:
![image](https://user-images.githubusercontent.com/133425/105461698-de05d380-5c8d-11eb-98ad-07d341447e78.png)


Visual Mode works also, however, I see problems on the settings page to select an icon for a button.
![image](https://user-images.githubusercontent.com/133425/105461814-04c40a00-5c8e-11eb-92f8-650b58f1363b.png)

Do you have more hints, have you an error inside the console? Is your screenshot above on the yellow line a problem?

**Comment by cargeo** [comment] 2021-01-22 09:05
The yellow line in the console is not an error, just the only thing I noticed.

In text mode the AddQuicktag dropdown is also not visible, but the button is (see „Test“):
<img width="945" alt="Screenshot 2021-01-22 at 9 57 47 AM" src="https://user-images.githubusercontent.com/14090070/105469800-0ba44a00-5c99-11eb-92cb-4eac3f507aa4.png">

Maybe its related to the WP jQuery version. When using the legacy jQuery version (jQuery Migrate Helper plugin) everything works fine.

**Comment by bueltge** [comment] 2021-01-22 11:59
I use a default WP installation, but WP 5.7-alpha, Development version. Maybe I will try them in WP 5.6 Stable.

**Comment by maryannk** [comment] 2021-02-18 17:19
I am also having this issue since updating to 5.6. I have Classic Editor running with classic as the default but allowing users to switch editors (switching this to not allowing users to switch editors had no effect). There is no Quicktags dropdown and no quicktag buttons are showing on the text tab.

![Edit_Post_‹_Foodie_Dev_—_WordPress](https://user-images.githubusercontent.com/1041690/108394989-5014fe00-71e3-11eb-9c34-d8125a077c69.jpg)

I tried installing jQuery Migrate but it didn't help. I'm happy to provide console screenshots if you tell me what to look for.

**Comment by maryannk** [comment] 2021-02-18 17:30
Update - this now seems to be working. When I was testing things, the custom quicktags got deleted (no idea how as I didn't deactivate or delete the quicktags plugin), but now that I have jquery migrate installed, readded the quicktags, and cleared the cache, the drop down is once again appearing in the editor.

**Comment by fenepedia** [comment] 2021-02-19 10:39
I have the same issue. Very strange is that it works on my computer and not on the computer of my client.
After clearing the cache, the bar was displayed a short period of time and then suddenly disappeared again.

So far, I could not reproduce the behavior on my own computer and browser.

**Comment by fenepedia** [comment] 2021-02-19 10:52
I  could reproduce the problem with my mac and safari.

I add some text to the post and hit "save". After finishing the saving-process the AddQuicktag dropdown disappeared.

To recover the AddQuicktag dropdown I opened the safari developer-console and cleared the cache.
As long as I leave the developer-console opened, there is no problem. After closing the developer-console and save the post again, the AddQuicktag dropdown disappeared.

**Comment by maryannk** [comment] 2021-02-19 16:35
I can confirm this same behavior. Since posting that the dropdown was back, it has disappeared and reappeared at different times when saving changes. I am using a MacBook Pro running Catalina and have tested the behavior in both Chrome and Firefox.

**Comment by bueltge** [comment] 2021-02-19 20:21
Thanks for these tests and helping notes about the behavior! I think I will fix the jQuery topic at first so that it runs in the current version of jQuery inside the WP core, version 3.5. After that, I will look for problems.

**Comment by fenepedia** [comment] 2021-03-22 10:25
@bueltge Do you have a timeline when you could fix this problem?

**Comment by bueltge** [comment] 2021-04-09 19:27
Hello at all. Sorry for waiting for feedback or an answer from my side, but the time is small and the task too much for me. However, for now there is an update inside the master branch. It would be great if you help me to test this first update, version 2.6.0-dev to find problems or give me the feedback that it works. The current update is only on the JavaScript side for the jQuery update of the WP core. I will also invest time to maintain the php code. I mean it is not necessary for the functionality, only for the maintenance, and maybe I will also check them for modern php version, like php 7.4 or 8.

So please download the master, upload in your plugin directory and activate it for testing. Deactivate your current version for testing.

**Comment by cargeo** [comment] 2021-04-12 07:06
I'm experiencing the same issue in 2.6.0-dev. No reliable AddQuicktag dropdown in editor. It's there when initially adding a new classic block, but it's gone after reload (like in [#49](https://github.com/bueltge/addquicktag/issues/49))

The icons on settings page are working now.

**Comment by fenepedia** [comment] 2021-04-19 12:21
Sorry for my late replay. With version 2.6.0-dev the problem still exists. It is the same problem as in comment https://github.com/bueltge/addquicktag/issues/48#issuecomment-781998538 written

**Comment by bueltge** [comment] 2021-04-19 16:08
I update also the TinyMCE plugin to add the select box inside the classic editor for now. I tested in several install and can't find any problems. Please test again with the current master of this repository. Thanks!

**Comment by cargeo** [comment] 2021-04-19 18:19
Latest version of 2.6.0-dev works! AddQuicktag dropdown is back in editor toolbar. Thank you 🙏

**Comment by fenepedia** [comment] 2021-04-23 09:48
Yes, i can confirm this. Latest dev works!

**Comment by bueltge** [comment] 2021-04-26 13:38
I add several changes to the code. So please would test it again and send your feedback here. After that, I will release this result on wp.org. Thanks a lot.

**Comment by cargeo** [comment] 2021-04-26 16:39
I tried your latest 2.6.0-dev: AddQuicktag dropdown is missing again.

**Comment by bueltge** [comment] 2021-04-26 18:07
What, I will test also again, but hope also for the test from @fenepedia 
I have no changes on the javascript of the plugin, only here and their maintenance in the PHP files.

**Comment by bueltge** [comment] 2021-04-29 18:02
After several tests from different peoples, I release now the new stable version 2.6.0
Thanks, @cargeo, and @fenepedia for your helping hands! ❤️

**Closed by bueltge** 2021-04-29 18:02 UTC
Labels: bug

**Comment by contaoacademy** [comment] 2021-09-06 15:11
Das Problem tritt gerade bei einer Installation erneut auf. Ich kann den Fehler allerdings bisher selbst nicht reproduzieren. Das Problem besteht nur bei einer Kundin.
Version: 2.6.1
Wordpress: 5.8

Hast sonst noch jemand das Problem?

**Comment by fenepedia** [comment] 2021-09-06 15:11
https://github.com/bueltge/addquicktag/issues/48

**Comment by fenepedia** [comment] 2021-09-06 15:11
https://github.com/bueltge/addquicktag/issues/48

**Comment by fenepedia** [comment] 2021-09-06 15:11
Das Problem tritt gerade bei einer Installation erneut auf. Ich kann den Fehler allerdings bisher selbst nicht reproduzieren. Das Problem besteht nur bei einer Kundin.
Version: 2.6.1
Wordpress: 5.8

Hast sonst noch jemand das Problem?

**Comment by bueltge** [comment] 2021-09-06 16:56
Cache hast du deaktiviert? Fehler in der Console des Browsers?

**Comment by fenepedia** [comment] 2021-09-16 12:27
Hallo Frank, das Problem hat sich erledigt. Kunde hat versehentlich die Werkzeugleiste ausgeblendet…

**Comment by bueltge** [comment] 2021-09-16 13:18
Danke für die Rückmeldung.
